version: '3.8'
services: 
  flask-db:
    container_name: mysql
    image: triomysql:latest
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - type: volume
      source: triomysql
      target: /var/lib/mysql
  flask-app:
    container_name: flask-app
    image: flask-app:latest
    build: ./flask-app
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
volumes:
  triomysql:
